package soa.model;
// Generated Feb 20, 2024, 10:53:18 AM by Hibernate Tools 4.3.6.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer personId;
	private String name;

	public Person() {
	}

	public Person(String name) {
		this.name = name;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
